### ISSUE TITLE
Add a view more button in the projects section

### ISSUE THREAD

**Issue by stephin007** [For-Community/forCommunity-official-website#18]

**Comment by stephin007** [comment]
when the user clicks son view more, the user should be routed to a new page that contains all the projects!

**Comment by Justinnn07** [comment]
OKAY BRO!
@stephin007

**Comment by dpshekhawat** [comment]
Hey I would like to contribute to this issue, please assign it to me.

**Comment by Justinnn07** [comment]
@dpshekhawat bro its done!

**Comment by dpshekhawat** [comment]
Okay!

**Comment by Justinnn07** [comment]
please check this **https://github.com/Justinnn07/calculator-made-using-python** @dpshekhawat

**Comment by stephin007** [comment]
hey @dpshekhawat , if you wanna join our comunity, Either mail us or join our discord using this
 [link](https://discord.gg/AEs3pafr2W)
