### ISSUE TITLE
Create or modify the Project card such that either on hovering over the project card it shows the percentage of all the tech stack used in the project  

### ISSUE THREAD

**Issue by vanshsehgal2001** [For-Community/forCommunity-official-website#27]
Create or modify the Project card such that either on hovering over the project card, all the texh stack percentages used in the project is displayed in the form of progress bar or on clicking the project card, a modal is there such that the project card opens in big size with tech details at the bottom of the card... Either way it would be good but doing by hovering would be impressive

**Comment by stephin007** [comment]
This is done by @vanshsehgal2001 in #31
