### ISSUE TITLE
Add a loading effect/component

### ISSUE THREAD

**Issue by stephin007** [For-Community/forCommunity-official-website#33]
**Is your feature request related to a problem? Please describe.**
Yes, when the members or projects are being fetched from the database, the section remains empty for 2 seconds.

**Describe the solution you'd like**
The solution is to add a LOading effect/component for the user to know that the data(in this case the members and the projects) is being fetched.

@vanshsehgal2001 you can take this as your next task!

**Comment by sagrawal9689** [comment]
Can I work on this issue. Can I use react bootstrap for loader.

**Comment by stephin007** [comment]
Yes, @sagrawal9689 please go ahead, its already assigned though, you can give it a shot though!
Also, if you wanna jjoin this community please mail us or join our discord using this [link](https://discord.gg/AEs3pafr2W)

**Comment by stephin007** [comment]
this issue is closed at #34
